name: Build and Push Latest Docker Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Build and Push Latest Docker Image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Build and push the latest Steel Browser API image
        run: |
          docker build -t ghcr.io/davidjameshowell/steel-browser-api:latest . -f ./api/Dockerfile
          docker push ghcr.io/davidjameshowellv/steel-browser-api:latest
      - name: Build and push the latest Steel Browser UI image
        run: |
          docker build -t ghcr.io/davidjameshowell/steel-browser-ui:latest . -f ./ui/Dockerfile
          docker push ghcr.io/davidjameshowell/steel-browser-ui:latest
